### ISSUE TITLE
Charts freeze and wrong time

### ISSUE THREAD

**Issue by 7jrxt42BxFZo4iAnN4CX** [akenshaw/flowsurface#18]
After some time, all the charts freeze except Candlestick.
How can I display debug logs?

And also on footprint and candlestick the time is UTC, but on heatmap and time&sales UTC+5-6 (this is not my time zone).

№1
> ![Screenshot_20240918_211330](https://github.com/user-attachments/assets/c3f6e6d6-9e91-469a-8360-4f71ce719393) 

№2
> ![Screenshot_20240918_212831](https://github.com/user-attachments/assets/78223a73-cb96-450a-a023-c5610eb60353)

**Comment by akenshaw** [comment]
Time zones for heatmap and time&sales are also in UTC, but their formatting is different. They are showing "minutes:seconds.milliseconds". I do see how it can create confusion though, might need to find ways to clarify this 

There should be a log file named "output.log", which is either in the root directory, where the src folder is, or inside the target directory.
I need more details on reproducing "charts freezing" though. Are you able to pan/zoom around on those charts after the freeze? Can you check that log file and see if an "ERROR" or "WARN" logs on loop?

**Comment by akenshaw** [comment]
indeed, it seems like a network condition problem. Looks like websocket instance was dropping some orderbook update packages, which was making the newer updates being in desync from the local orderbook. If this was a very rare occasion, like it only happened once or in a specific time, it probably caused by the exchange itself is my guess

Streaming orderbook with reasonable levels from Binance is a bit tricky, we have to be in-sync the whole way, or we have to fetch 1000 bid ask levels from the rest api all over again, while trying to sync it with the data coming from websocket. Further looking at it, i've realized that it is actually missing some "self-healing" steps while trying to maintain the sync on situations where packages dropped. So thanks for bringing up this issue!

**Comment by akenshaw** [comment]
0776c9f43daee5bb4288664d10d8e38e7e9dffd1 should be fixing this issue
